M48
; DRILL file {KiCad 8.0.8} date 2025-03-21T07:08:34+0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-21T07:08:34+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X1.1122Y-0.874
X1.122Y-1.7795
X2.4311Y-1.7894
X2.4508Y-0.874
M30
